"""OAuth 2.0 flow для Google APIs.

Чиста обгортка над google-auth-oauthlib без залежності від Streamlit —
щоб можна було тестувати окремо й перевикористовувати поза UI.
"""
from __future__ import annotations

import os
import tempfile
from pathlib import Path
from typing import cast

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build

from core.logger import get_logger, log_call

log = get_logger(__name__)

CREDENTIALS_PATH = Path("config") / "credentials.json"
REDIRECT_URI = "http://localhost:8501"
# PKCE verifier зберігаємо у temp-файлі, бо Streamlit session_state
# не виживає browser redirect (TODO Week 4: cookie-based для Cloud Run).
VERIFIER_PATH = Path(tempfile.gettempdir()) / "survey-insight-oauth-verifier"

IDENTITY_SCOPES = [
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
]

# Scopes для роботи з Forms+Drive+Sheets API. Додаються incrementally
# після identity-логіну: Google показує другий consent screen лише на
# delta-scopes завдяки include_granted_scopes='true'.
API_SCOPES = IDENTITY_SCOPES + [
    "https://www.googleapis.com/auth/forms.body.readonly",
    "https://www.googleapis.com/auth/forms.responses.readonly",
    "https://www.googleapis.com/auth/drive.metadata.readonly",
    "https://www.googleapis.com/auth/spreadsheets.readonly",
]


def has_api_scopes(creds_dict: dict | None) -> bool:
    """Чи містить поточний token усі API-scopes (для гейту UI)."""
    if not creds_dict:
        return False
    granted = set(creds_dict.get("scopes") or [])
    return all(scope in granted for scope in API_SCOPES)


def _configure_oauthlib_env() -> None:
    """Виставити env-флаги oauthlib для нашого web-flow.

    - INSECURE_TRANSPORT: дозволити HTTP-redirect на localhost (для dev).
      На Cloud Run у Тиждень 4+ цей флаг знімаємо — там буде HTTPS.
    - RELAX_TOKEN_SCOPE: не падати, якщо Google повертає інакший набір
      scopes ніж ми запитали (норма для incremental authorization, де
      identity-grant перекаже разом із новими scopes).
    """
    os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"
    os.environ["OAUTHLIB_RELAX_TOKEN_SCOPE"] = "1"


def build_flow(scopes: list[str], code_verifier: str | None = None) -> Flow:
    """Створити OAuth Flow з credentials.json.

    Args:
        scopes: список OAuth scopes.
        code_verifier: PKCE verifier — обовʼязково передати у callback'у
            той самий, що був при генерації auth_url, інакше Google поверне
            invalid_grant. Якщо None — flow згенерує новий (для auth_url-фази).
    """
    _configure_oauthlib_env()
    flow = Flow.from_client_secrets_file(
        str(CREDENTIALS_PATH),
        scopes=scopes,
        redirect_uri=REDIRECT_URI,
    )
    if code_verifier:
        flow.code_verifier = code_verifier
    return flow


def get_auth_url(flow: Flow) -> tuple[str, str]:
    """Згенерувати URL для редиректу на Google consent screen.

    Returns:
        (auth_url, code_verifier) — verifier треба персистувати у файл
        і дістати при callback'у, щоб exchange_code пройшов PKCE-перевірку.
    """
    auth_url, _state = flow.authorization_url(
        access_type="offline",
        include_granted_scopes="true",
        prompt="consent",
    )
    # state не зберігаємо: див. _handle_oauth_callback щодо CSRF-стратегії.
    verifier = flow.code_verifier
    if verifier is None:
        raise RuntimeError("PKCE code_verifier was not generated by Flow.")
    return auth_url, verifier


def save_verifier(verifier: str) -> None:
    """Записати PKCE verifier у temp-файл для відновлення у callback'у."""
    VERIFIER_PATH.write_text(verifier, encoding="utf-8")


def load_verifier() -> str | None:
    """Прочитати збережений PKCE verifier (None якщо нема)."""
    if not VERIFIER_PATH.exists():
        return None
    return VERIFIER_PATH.read_text(encoding="utf-8").strip() or None


def clear_verifier() -> None:
    """Видалити збережений PKCE verifier після успішного exchange."""
    VERIFIER_PATH.unlink(missing_ok=True)


def exchange_code(flow: Flow, code: str) -> Credentials:
    """Обміняти authorization code на токени."""
    flow.fetch_token(code=code)
    # Flow.credentials у нашому web-flow завжди oauth2.Credentials,
    # не ExternalAccountAuthorizedUserCredentials — звужуємо тип для Pylance.
    return cast(Credentials, flow.credentials)


def credentials_to_dict(creds: Credentials) -> dict:
    """Серіалізувати Credentials у JSON-сумісний dict для session_state."""
    return {
        "token": creds.token,
        "refresh_token": creds.refresh_token,
        "token_uri": creds.token_uri,
        "client_id": creds.client_id,
        "client_secret": creds.client_secret,
        "scopes": creds.scopes,
    }


def credentials_from_dict(data: dict) -> Credentials:
    """Відновити Credentials з dict (зворот до credentials_to_dict)."""
    return Credentials(
        token=data.get("token"),
        refresh_token=data.get("refresh_token"),
        token_uri=data.get("token_uri"),
        client_id=data.get("client_id"),
        client_secret=data.get("client_secret"),
        scopes=data.get("scopes"),
    )


def refresh_if_needed(creds: Credentials) -> Credentials:
    """Оновити access token, якщо він прострочений."""
    if creds.expired and creds.refresh_token:
        creds.refresh(Request())
    return creds


def get_user_info(creds: Credentials) -> dict:
    """Дістати email/name/picture через oauth2 v2 userinfo endpoint."""
    service = build("oauth2", "v2", credentials=creds, cache_discovery=False)
    with log_call("api_call_ok", target="oauth.userinfo", logger=log):
        return service.userinfo().get().execute()
